spring:
  application:
    name: stock
  jpa:
    hibernate:
      ddl-auto: create
    show-sql:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_example
    username: root
    password: root
    hikari:
      maximum-pool-size: 40

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace